version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    container_name: refer_eth_mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    networks:
      - refer-eth-network


  backend:
    image: refer-eth-backend:latest
    container_name: refer-eth-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    networks:
      - refer-eth-network

networks:
  refer-eth-network:
